"use client";import{useEffect,useState}from"react";
type L="en"|"zh"|"de"|"ko"|"fr";type I={id:string;type:"publication"|"book"|"software"|"about";title:string;titleZh?:string;titleDe?:string;titleKo?:string;titleFr?:string;summary?:string;venue?:string;year?:number;tags?:string[];publisherUrl?:string;codeUrl?:string;coverFileId?:string;attachmentIds?:string[]};
const text={en:["Home","Publications","Books","Softwares","About","Engineering Intelligence, Computational Mechanics, and the Future of Simulation","Advancing geometry-aware computation, intelligent engineering software, and trustworthy scientific AI.","Explore publications","Selected Publications","Books & Monographs","Research Software","About Marcus"],zh:["首页","论文","著作","软件","关于","工程智能、计算力学与仿真的未来","推进几何感知计算、智能工程软件与可信科学人工智能研究。","浏览论文","代表性论文","著作与专著","科研软件","关于 Marcus"],de:["Start","Publikationen","Bücher","Software","Über mich","Engineering Intelligence, Mechanik und die Zukunft der Simulation","Geometriebewusste Berechnung, intelligente Ingenieursoftware und wissenschaftliche KI.","Publikationen entdecken","Ausgewählte Publikationen","Bücher & Monografien","Forschungssoftware","Über Marcus"],ko:["홈","논문","저서","소프트웨어","소개","공학 지능, 전산역학, 그리고 시뮬레이션의 미래","기하 인식 계산, 지능형 공학 소프트웨어 및 과학 AI 연구.","논문 살펴보기","주요 논문","저서 및 단행본","연구 소프트웨어","Marcus 소개"],fr:["Accueil","Publications","Livres","Logiciels","À propos","Intelligence d’ingénierie, mécanique numérique et avenir de la simulation","Calcul sensible à la géométrie, logiciels intelligents et IA scientifique.","Découvrir les publications","Publications choisies","Livres & Monographies","Logiciels de recherche","À propos de Marcus"]}as const;
const demo:I[]=[{id:"1",type:"publication",title:"Geometry-aware neural operators for intelligent structural simulation",venue:"Computational Mechanics",year:2026,tags:["Neural operators","Geometry","Simulation"]},{id:"2",type:"publication",title:"Spline-based intelligence for nonlinear and multiscale mechanics",venue:"CMAME",year:2025,tags:["Splines","Mechanics","Multiscale"]},{id:"3",type:"book",title:"Engineering Intelligence",summary:"Geometry, Mechanics, and Scientific AI",year:2026},{id:"4",type:"software",title:"DUTF",summary:"An intelligent CAE platform for geometry, simulation, and engineering decision-making."}];
const Figure=()=> <div className="figure"><i/><i/><i/><b/><b/><b/></div>;const title=(x:I,l:L)=>(l==="zh"?x.titleZh:l==="de"?x.titleDe:l==="ko"?x.titleKo:l==="fr"?x.titleFr:x.title)||x.title;
export default function Home(){const[l,setL]=useState<L>("en"),[items,setItems]=useState(demo);useEffect(()=>{fetch("/api/content").then(r=>r.json()).then(x=>x.items?.length&&setItems(x.items)).catch(()=>{})},[]);const t=text[l],go=(x:string)=>document.getElementById(x)?.scrollIntoView({behavior:"smooth"}),pubs=items.filter(x=>x.type==="publication"),books=items.filter(x=>x.type==="book"),soft=items.filter(x=>x.type==="software");return <main><header><button className="wordmark" onClick={()=>go("home")}>Marcus Chuk</button><nav>{["home","publications","books","softwares","about"].map((x,i)=><button key={x} onClick={()=>go(x)}>{t[i]}</button>)}</nav><div className="langs">{([["en","EN"],["zh","中文"],["de","DE"],["ko","한국어"],["fr","FR"]]as[L,string][]).map(([x,n])=><button className={x===l?"active":""} key={x} onClick={()=>setL(x)}>{n}</button>)}</div></header>
<section id="home" className="hero"><div><p className="eyebrow">PROFESSOR · RESEARCHER · SOFTWARE ARCHITECT</p><h1>{t[5]}</h1><p className="lede">{t[6]}</p><button className="cta" onClick={()=>go("publications")}>{t[7]} ↗</button></div><Figure/></section>
<Section id="publications" n="01 / PUBLICATION" title={t[8]}><div>{pubs.map((x,i)=><article className="publication" key={x.id}><div className="visual">{x.coverFileId?<img src={`/api/files/${x.coverFileId}`} alt=""/>:<Figure/>}<small>{String(i+1).padStart(2,"0")}</small></div><div className="pcopy"><p>{x.year} · {x.venue}</p><h3>{title(x,l)}</h3><p>{x.summary}</p><div className="tags">{x.tags?.map(q=><span key={q}>{q}</span>)}</div><div className="links">{x.publisherUrl&&<a href={x.publisherUrl}>Publisher ↗</a>}{x.attachmentIds?.map((q,j)=><a key={q} href={`/api/files/${q}`}>File {j+1} ↗</a>)}{x.codeUrl&&<a href={x.codeUrl}>Code ↗</a>}</div></div></article>)}</div></Section>
<Section id="books" n="02 / BOOK" title={t[9]}><div className="cards">{books.map(x=><article className="book" key={x.id}>{x.coverFileId&&<img src={`/api/files/${x.coverFileId}`} alt=""/>}<small>{x.year}</small><h3>{title(x,l)}</h3><p>{x.summary}</p></article>)}</div></Section>
<Section id="softwares" n="03 / SOFTWARE" title={t[10]}><div className="cards software">{soft.map(x=><article key={x.id}><b>{x.title.slice(0,2)}</b><h3>{title(x,l)}</h3><p>{x.summary}</p>{x.publisherUrl&&<a href={x.publisherUrl}>Documentation ↗</a>}</article>)}</div></Section>
<section id="about" className="about"><div className="portrait">MC</div><div><p>04 / ABOUT</p><h2>{t[11]}</h2><p className="about-text">{items.find(x=>x.type==="about")?.summary||"Marcus Chuk is a researcher working across computational mechanics, engineering intelligence, and next-generation simulation software."}</p></div></section><footer><span className="wordmark">Marcus Chuk</span><span>Engineering Intelligence · Computational Mechanics</span><a className="admin-entry" href="/admin"><small>ADMIN</small><strong>后台管理 ↗</strong></a><span>© 2026</span></footer></main>}
function Section({id,n,title,children}:{id:string;n:string;title:string;children:React.ReactNode}){return <section id={id} className="content"><div className="heading"><p>{n}</p><h2>{title}</h2></div>{children}</section>}
