type SiteEnv={DB:D1Database;BUCKET:R2Bucket};
function env(){const x=(globalThis as typeof globalThis&{__MARCUS_SITE_ENV?:SiteEnv}).__MARCUS_SITE_ENV;if(!x)throw new Error("Storage unavailable");return x}
export type Content={id:string;type:"publication"|"book"|"software"|"about";title:string;titleZh?:string;titleDe?:string;titleKo?:string;titleFr?:string;summary?:string;venue?:string;year?:number;tags?:string[];publisherUrl?:string;codeUrl?:string;coverFileId?:string;attachmentIds?:string[];status:"draft"|"published";sortOrder:number};
let ready=false;
export async function init(){if(ready)return;const {DB}=env();await DB.batch([
DB.prepare(`CREATE TABLE IF NOT EXISTS content_items(id TEXT PRIMARY KEY,type TEXT NOT NULL,title TEXT NOT NULL,title_zh TEXT,title_de TEXT,title_ko TEXT,title_fr TEXT,summary TEXT,venue TEXT,year INTEGER,tags TEXT,publisher_url TEXT,code_url TEXT,cover_file_id TEXT,attachment_ids TEXT,status TEXT NOT NULL DEFAULT 'published',sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`),
DB.prepare(`CREATE TABLE IF NOT EXISTS files(id TEXT PRIMARY KEY,object_key TEXT NOT NULL UNIQUE,filename TEXT NOT NULL,content_type TEXT NOT NULL,size INTEGER NOT NULL,kind TEXT NOT NULL,created_at TEXT NOT NULL)`),
DB.prepare(`CREATE INDEX IF NOT EXISTS content_order_idx ON content_items(type,sort_order,year)`) ]);ready=true}
const map=(r:Record<string,unknown>):Content=>({id:String(r.id),type:r.type as Content["type"],title:String(r.title),titleZh:r.title_zh as string,titleDe:r.title_de as string,titleKo:r.title_ko as string,titleFr:r.title_fr as string,summary:r.summary as string,venue:r.venue as string,year:r.year?Number(r.year):undefined,tags:r.tags?JSON.parse(String(r.tags)):[],publisherUrl:r.publisher_url as string,codeUrl:r.code_url as string,coverFileId:r.cover_file_id as string,attachmentIds:r.attachment_ids?JSON.parse(String(r.attachment_ids)):[],status:r.status as Content["status"],sortOrder:Number(r.sort_order||0)});
export async function list(drafts=false){await init();const x=await env().DB.prepare(`SELECT * FROM content_items ${drafts?"":"WHERE status='published'"} ORDER BY sort_order,year DESC,updated_at DESC`).all();return(x.results as Record<string,unknown>[]).map(map)}
export async function save(b:Partial<Content>&Pick<Content,"title"|"type">,id=crypto.randomUUID()){await init();const now=new Date().toISOString();const old=await env().DB.prepare("SELECT created_at FROM content_items WHERE id=?").bind(id).first();await env().DB.prepare(`INSERT INTO content_items(id,type,title,title_zh,title_de,title_ko,title_fr,summary,venue,year,tags,publisher_url,code_url,cover_file_id,attachment_ids,status,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET type=excluded.type,title=excluded.title,title_zh=excluded.title_zh,title_de=excluded.title_de,title_ko=excluded.title_ko,title_fr=excluded.title_fr,summary=excluded.summary,venue=excluded.venue,year=excluded.year,tags=excluded.tags,publisher_url=excluded.publisher_url,code_url=excluded.code_url,cover_file_id=excluded.cover_file_id,attachment_ids=excluded.attachment_ids,status=excluded.status,sort_order=excluded.sort_order,updated_at=excluded.updated_at`).bind(id,b.type,b.title,b.titleZh||null,b.titleDe||null,b.titleKo||null,b.titleFr||null,b.summary||null,b.venue||null,b.year||null,JSON.stringify(b.tags||[]),b.publisherUrl||null,b.codeUrl||null,b.coverFileId||null,JSON.stringify(b.attachmentIds||[]),b.status||"published",b.sortOrder||0,(old?.created_at as string)||now,now).run();return id}
export async function remove(id:string){await init();await env().DB.prepare("DELETE FROM content_items WHERE id=?").bind(id).run()}
export async function upload(file:File){await init();const id=crypto.randomUUID(),name=file.name.replace(/[^a-zA-Z0-9._-]/g,"_").slice(-160),key=`uploads/${id}-${name}`,kind=file.type.startsWith("image/")?"image":"document",now=new Date().toISOString();await env().BUCKET.put(key,file.stream(),{httpMetadata:{contentType:file.type||"application/octet-stream"}});await env().DB.prepare("INSERT INTO files(id,object_key,filename,content_type,size,kind,created_at) VALUES(?,?,?,?,?,?,?)").bind(id,key,file.name,file.type||"application/octet-stream",file.size,kind,now).run();return{id,filename:file.name,size:file.size,kind}}
export async function getFile(id:string){await init();return env().DB.prepare("SELECT * FROM files WHERE id=?").bind(id).first<Record<string,unknown>>()}
export function bucket(){return env().BUCKET}
